# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/PROJECTS/SuperPong-FPGA/src/bd/hdmi/ip/hdmi_xbar_1/hdmi_xbar_1.xci
# IP: The module: 'hdmi_xbar_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/PROJECTS/SuperPong-FPGA/src/bd/hdmi/ip/hdmi_xbar_1/hdmi_xbar_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'hdmi_xbar_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# IP: D:/PROJECTS/SuperPong-FPGA/src/bd/hdmi/ip/hdmi_xbar_1/hdmi_xbar_1.xci
# IP: The module: 'hdmi_xbar_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/PROJECTS/SuperPong-FPGA/src/bd/hdmi/ip/hdmi_xbar_1/hdmi_xbar_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'hdmi_xbar_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
