# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_msg_config -id {Common 17-41} -limit 10000000
create_project -in_memory -part xc7a200tsbg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/PROJECTS/FPGAImageProcessing/DMASys_2018/DMASys_2018.cache/wt [current_project]
set_property parent.project_path D:/PROJECTS/FPGAImageProcessing/DMASys_2018/DMASys_2018.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:nexys_video:part0:1.2 [current_project]
set_property ip_repo_paths d:/PROJECTS/FPGAImageProcessing/Inverter [current_project]
update_ip_catalog
set_property ip_output_repo d:/PROJECTS/FPGAImageProcessing/DMASys_2018/DMASys_2018.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib D:/PROJECTS/FPGAImageProcessing/DMASys_2018/DMASys_2018.srcs/sources_1/bd/design_1/hdl/design_1_wrapper.v
add_files D:/PROJECTS/FPGAImageProcessing/DMASys_2018/DMASys_2018.srcs/sources_1/bd/design_1/design_1.bd
set_property used_in_implementation false [get_files -all d:/PROJECTS/FPGAImageProcessing/DMASys_2018/DMASys_2018.srcs/sources_1/bd/design_1/ip/design_1_microblaze_0_3/design_1_microblaze_0_3.xdc]
set_property used_in_implementation false [get_files -all d:/PROJECTS/FPGAImageProcessing/DMASys_2018/DMASys_2018.srcs/sources_1/bd/design_1/ip/design_1_microblaze_0_3/design_1_microblaze_0_3_ooc_debug.xdc]
set_property used_in_implementation false [get_files -all d:/PROJECTS/FPGAImageProcessing/DMASys_2018/DMASys_2018.srcs/sources_1/bd/design_1/ip/design_1_microblaze_0_3/design_1_microblaze_0_3_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/PROJECTS/FPGAImageProcessing/DMASys_2018/DMASys_2018.srcs/sources_1/bd/design_1/ip/design_1_dlmb_v10_4/design_1_dlmb_v10_4.xdc]
set_property used_in_implementation false [get_files -all d:/PROJECTS/FPGAImageProcessing/DMASys_2018/DMASys_2018.srcs/sources_1/bd/design_1/ip/design_1_dlmb_v10_4/design_1_dlmb_v10_4_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/PROJECTS/FPGAImageProcessing/DMASys_2018/DMASys_2018.srcs/sources_1/bd/design_1/ip/design_1_ilmb_v10_4/design_1_ilmb_v10_4.xdc]
set_property used_in_implementation false [get_files -all d:/PROJECTS/FPGAImageProcessing/DMASys_2018/DMASys_2018.srcs/sources_1/bd/design_1/ip/design_1_ilmb_v10_4/design_1_ilmb_v10_4_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/PROJECTS/FPGAImageProcessing/DMASys_2018/DMASys_2018.srcs/sources_1/bd/design_1/ip/design_1_dlmb_bram_if_cntlr_4/design_1_dlmb_bram_if_cntlr_4_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/PROJECTS/FPGAImageProcessing/DMASys_2018/DMASys_2018.srcs/sources_1/bd/design_1/ip/design_1_ilmb_bram_if_cntlr_4/design_1_ilmb_bram_if_cntlr_4_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/PROJECTS/FPGAImageProcessing/DMASys_2018/DMASys_2018.srcs/sources_1/bd/design_1/ip/design_1_lmb_bram_4/design_1_lmb_bram_4_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/PROJECTS/FPGAImageProcessing/DMASys_2018/DMASys_2018.srcs/sources_1/bd/design_1/ip/design_1_xbar_3/design_1_xbar_3_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/PROJECTS/FPGAImageProcessing/DMASys_2018/DMASys_2018.srcs/sources_1/bd/design_1/ip/design_1_microblaze_0_axi_intc_4/design_1_microblaze_0_axi_intc_4.xdc]
set_property used_in_implementation false [get_files -all d:/PROJECTS/FPGAImageProcessing/DMASys_2018/DMASys_2018.srcs/sources_1/bd/design_1/ip/design_1_microblaze_0_axi_intc_4/design_1_microblaze_0_axi_intc_4_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/PROJECTS/FPGAImageProcessing/DMASys_2018/DMASys_2018.srcs/sources_1/bd/design_1/ip/design_1_microblaze_0_axi_intc_4/design_1_microblaze_0_axi_intc_4_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/PROJECTS/FPGAImageProcessing/DMASys_2018/DMASys_2018.srcs/sources_1/bd/design_1/ip/design_1_mdm_1_4/design_1_mdm_1_4.xdc]
set_property used_in_implementation false [get_files -all d:/PROJECTS/FPGAImageProcessing/DMASys_2018/DMASys_2018.srcs/sources_1/bd/design_1/ip/design_1_mdm_1_4/design_1_mdm_1_4_ooc_trace.xdc]
set_property used_in_implementation false [get_files -all d:/PROJECTS/FPGAImageProcessing/DMASys_2018/DMASys_2018.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1_4/design_1_clk_wiz_1_4_board.xdc]
set_property used_in_implementation false [get_files -all d:/PROJECTS/FPGAImageProcessing/DMASys_2018/DMASys_2018.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1_4/design_1_clk_wiz_1_4.xdc]
set_property used_in_implementation false [get_files -all d:/PROJECTS/FPGAImageProcessing/DMASys_2018/DMASys_2018.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1_4/design_1_clk_wiz_1_4_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/PROJECTS/FPGAImageProcessing/DMASys_2018/DMASys_2018.srcs/sources_1/bd/design_1/ip/design_1_rst_clk_wiz_1_100M_4/design_1_rst_clk_wiz_1_100M_4_board.xdc]
set_property used_in_implementation false [get_files -all d:/PROJECTS/FPGAImageProcessing/DMASys_2018/DMASys_2018.srcs/sources_1/bd/design_1/ip/design_1_rst_clk_wiz_1_100M_4/design_1_rst_clk_wiz_1_100M_4.xdc]
set_property used_in_implementation false [get_files -all d:/PROJECTS/FPGAImageProcessing/DMASys_2018/DMASys_2018.srcs/sources_1/bd/design_1/ip/design_1_rst_clk_wiz_1_100M_4/design_1_rst_clk_wiz_1_100M_4_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/PROJECTS/FPGAImageProcessing/DMASys_2018/DMASys_2018.srcs/sources_1/bd/design_1/ip/design_1_axi_uartlite_0_1/design_1_axi_uartlite_0_1_board.xdc]
set_property used_in_implementation false [get_files -all d:/PROJECTS/FPGAImageProcessing/DMASys_2018/DMASys_2018.srcs/sources_1/bd/design_1/ip/design_1_axi_uartlite_0_1/design_1_axi_uartlite_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/PROJECTS/FPGAImageProcessing/DMASys_2018/DMASys_2018.srcs/sources_1/bd/design_1/ip/design_1_axi_uartlite_0_1/design_1_axi_uartlite_0_1.xdc]
set_property used_in_implementation false [get_files -all d:/PROJECTS/FPGAImageProcessing/DMASys_2018/DMASys_2018.srcs/sources_1/bd/design_1/ip/design_1_mig_7series_0_3/design_1_mig_7series_0_3/user_design/constraints/design_1_mig_7series_0_3.xdc]
set_property used_in_implementation false [get_files -all d:/PROJECTS/FPGAImageProcessing/DMASys_2018/DMASys_2018.srcs/sources_1/bd/design_1/ip/design_1_mig_7series_0_3/design_1_mig_7series_0_3/user_design/constraints/design_1_mig_7series_0_3_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/PROJECTS/FPGAImageProcessing/DMASys_2018/DMASys_2018.srcs/sources_1/bd/design_1/ip/design_1_mig_7series_0_3/design_1_mig_7series_0_3_board.xdc]
set_property used_in_implementation false [get_files -all d:/PROJECTS/FPGAImageProcessing/DMASys_2018/DMASys_2018.srcs/sources_1/bd/design_1/ip/design_1_rst_mig_7series_0_100M_2/design_1_rst_mig_7series_0_100M_2_board.xdc]
set_property used_in_implementation false [get_files -all d:/PROJECTS/FPGAImageProcessing/DMASys_2018/DMASys_2018.srcs/sources_1/bd/design_1/ip/design_1_rst_mig_7series_0_100M_2/design_1_rst_mig_7series_0_100M_2.xdc]
set_property used_in_implementation false [get_files -all d:/PROJECTS/FPGAImageProcessing/DMASys_2018/DMASys_2018.srcs/sources_1/bd/design_1/ip/design_1_rst_mig_7series_0_100M_2/design_1_rst_mig_7series_0_100M_2_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/PROJECTS/FPGAImageProcessing/DMASys_2018/DMASys_2018.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_0_3/design_1_axi_dma_0_3_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/PROJECTS/FPGAImageProcessing/DMASys_2018/DMASys_2018.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_0_3/design_1_axi_dma_0_3.xdc]
set_property used_in_implementation false [get_files -all d:/PROJECTS/FPGAImageProcessing/DMASys_2018/DMASys_2018.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_0_3/design_1_axi_dma_0_3_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/PROJECTS/FPGAImageProcessing/DMASys_2018/DMASys_2018.srcs/sources_1/bd/design_1/ip/design_1_auto_pc_3/design_1_auto_pc_3_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/PROJECTS/FPGAImageProcessing/DMASys_2018/DMASys_2018.srcs/sources_1/bd/design_1/ip/design_1_auto_pc_4/design_1_auto_pc_4_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/PROJECTS/FPGAImageProcessing/DMASys_2018/DMASys_2018.srcs/sources_1/bd/design_1/ip/design_1_auto_pc_0/design_1_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/PROJECTS/FPGAImageProcessing/DMASys_2018/DMASys_2018.srcs/sources_1/bd/design_1/ip/design_1_auto_pc_1/design_1_auto_pc_1_ooc.xdc]
set_property used_in_synthesis false [get_files -all d:/PROJECTS/FPGAImageProcessing/DMASys_2018/DMASys_2018.srcs/sources_1/bd/design_1/ip/design_1_auto_cc_0/design_1_auto_cc_0_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/PROJECTS/FPGAImageProcessing/DMASys_2018/DMASys_2018.srcs/sources_1/bd/design_1/ip/design_1_auto_cc_0/design_1_auto_cc_0_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/PROJECTS/FPGAImageProcessing/DMASys_2018/DMASys_2018.srcs/sources_1/bd/design_1/ip/design_1_auto_cc_0/design_1_auto_cc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/PROJECTS/FPGAImageProcessing/DMASys_2018/DMASys_2018.srcs/sources_1/bd/design_1/ip/design_1_auto_pc_2/design_1_auto_pc_2_ooc.xdc]
set_property used_in_implementation false [get_files -all D:/PROJECTS/FPGAImageProcessing/DMASys_2018/DMASys_2018.srcs/sources_1/bd/design_1/design_1_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top design_1_wrapper -part xc7a200tsbg484-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef design_1_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file design_1_wrapper_utilization_synth.rpt -pb design_1_wrapper_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
