# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/design_1/design_1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_microblaze_0_3/design_1_microblaze_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_microblaze_0_3 || ORIG_REF_NAME==design_1_microblaze_0_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_dlmb_v10_4/design_1_dlmb_v10_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_dlmb_v10_4 || ORIG_REF_NAME==design_1_dlmb_v10_4} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ilmb_v10_4/design_1_ilmb_v10_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_ilmb_v10_4 || ORIG_REF_NAME==design_1_ilmb_v10_4} -quiet] -quiet

# IP: bd/design_1/ip/design_1_dlmb_bram_if_cntlr_4/design_1_dlmb_bram_if_cntlr_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_dlmb_bram_if_cntlr_4 || ORIG_REF_NAME==design_1_dlmb_bram_if_cntlr_4} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ilmb_bram_if_cntlr_4/design_1_ilmb_bram_if_cntlr_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_ilmb_bram_if_cntlr_4 || ORIG_REF_NAME==design_1_ilmb_bram_if_cntlr_4} -quiet] -quiet

# IP: bd/design_1/ip/design_1_lmb_bram_4/design_1_lmb_bram_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_lmb_bram_4 || ORIG_REF_NAME==design_1_lmb_bram_4} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xbar_3/design_1_xbar_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xbar_3 || ORIG_REF_NAME==design_1_xbar_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_microblaze_0_axi_periph_4/design_1_microblaze_0_axi_periph_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_microblaze_0_axi_periph_4 || ORIG_REF_NAME==design_1_microblaze_0_axi_periph_4} -quiet] -quiet

# IP: bd/design_1/ip/design_1_microblaze_0_axi_intc_4/design_1_microblaze_0_axi_intc_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_microblaze_0_axi_intc_4 || ORIG_REF_NAME==design_1_microblaze_0_axi_intc_4} -quiet] -quiet

# IP: bd/design_1/ip/design_1_microblaze_0_xlconcat_4/design_1_microblaze_0_xlconcat_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_microblaze_0_xlconcat_4 || ORIG_REF_NAME==design_1_microblaze_0_xlconcat_4} -quiet] -quiet

# IP: bd/design_1/ip/design_1_mdm_1_4/design_1_mdm_1_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_mdm_1_4 || ORIG_REF_NAME==design_1_mdm_1_4} -quiet] -quiet

# IP: bd/design_1/ip/design_1_clk_wiz_1_4/design_1_clk_wiz_1_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_clk_wiz_1_4 || ORIG_REF_NAME==design_1_clk_wiz_1_4} -quiet] -quiet

# IP: bd/design_1/ip/design_1_rst_clk_wiz_1_100M_4/design_1_rst_clk_wiz_1_100M_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_rst_clk_wiz_1_100M_4 || ORIG_REF_NAME==design_1_rst_clk_wiz_1_100M_4} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_uartlite_0_1/design_1_axi_uartlite_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_uartlite_0_1 || ORIG_REF_NAME==design_1_axi_uartlite_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_mig_7series_0_3/design_1_mig_7series_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_mig_7series_0_3 || ORIG_REF_NAME==design_1_mig_7series_0_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_rst_mig_7series_0_100M_2/design_1_rst_mig_7series_0_100M_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_rst_mig_7series_0_100M_2 || ORIG_REF_NAME==design_1_rst_mig_7series_0_100M_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_inverter_0_3/design_1_inverter_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_inverter_0_3 || ORIG_REF_NAME==design_1_inverter_0_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_dma_0_3/design_1_axi_dma_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_dma_0_3 || ORIG_REF_NAME==design_1_axi_dma_0_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_pc_3/design_1_auto_pc_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_pc_3 || ORIG_REF_NAME==design_1_auto_pc_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_pc_4/design_1_auto_pc_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_pc_4 || ORIG_REF_NAME==design_1_auto_pc_4} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_pc_0/design_1_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_pc_0 || ORIG_REF_NAME==design_1_auto_pc_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_pc_1/design_1_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_pc_1 || ORIG_REF_NAME==design_1_auto_pc_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_cc_0/design_1_auto_cc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_cc_0 || ORIG_REF_NAME==design_1_auto_cc_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_pc_2/design_1_auto_pc_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_pc_2 || ORIG_REF_NAME==design_1_auto_pc_2} -quiet] -quiet

# XDC: bd/design_1/design_1_ooc.xdc
