# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Public/Vivado_Projects/Nexys-Video-HDMI/src/bd/hdmi/ip/hdmi_PmodJSTK2_1_0_1/hdmi_PmodJSTK2_1_0.xci
# IP: The module: 'hdmi_PmodJSTK2_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/Public/Vivado_Projects/Nexys-Video-HDMI/src/bd/hdmi/ip/hdmi_PmodJSTK2_1_0_1/src/PmodJSTK2_pmod_bridge_0_0/PmodJSTK2_pmod_bridge_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PmodJSTK2_pmod_bridge_0_0 || ORIG_REF_NAME==PmodJSTK2_pmod_bridge_0_0}]

# IP: c:/Users/Public/Vivado_Projects/Nexys-Video-HDMI/src/bd/hdmi/ip/hdmi_PmodJSTK2_1_0_1/src/PmodJSTK2_axi_quad_spi_0_0/PmodJSTK2_axi_quad_spi_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PmodJSTK2_axi_quad_spi_0_0 || ORIG_REF_NAME==PmodJSTK2_axi_quad_spi_0_0}]

# XDC: c:/Users/Public/Vivado_Projects/Nexys-Video-HDMI/src/bd/hdmi/ip/hdmi_PmodJSTK2_1_0_1/hdmi_PmodJSTK2_1_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'hdmi_PmodJSTK2_1_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: c:/Users/Public/Vivado_Projects/Nexys-Video-HDMI/src/bd/hdmi/ip/hdmi_PmodJSTK2_1_0_1/src/PmodJSTK2_pmod_bridge_0_0/PmodJSTK2_pmod_bridge_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodJSTK2_pmod_bridge_0_0 || ORIG_REF_NAME==PmodJSTK2_pmod_bridge_0_0}] {/inst }]/inst ]]

# XDC: c:/Users/Public/Vivado_Projects/Nexys-Video-HDMI/src/bd/hdmi/ip/hdmi_PmodJSTK2_1_0_1/src/PmodJSTK2_pmod_bridge_0_0/src/pmod_concat_ooc.xdc

# XDC: c:/Users/Public/Vivado_Projects/Nexys-Video-HDMI/src/bd/hdmi/ip/hdmi_PmodJSTK2_1_0_1/src/PmodJSTK2_axi_quad_spi_0_0/PmodJSTK2_axi_quad_spi_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodJSTK2_axi_quad_spi_0_0 || ORIG_REF_NAME==PmodJSTK2_axi_quad_spi_0_0}] {/U0 }]/U0 ]]

# XDC: c:/Users/Public/Vivado_Projects/Nexys-Video-HDMI/src/bd/hdmi/ip/hdmi_PmodJSTK2_1_0_1/src/PmodJSTK2_axi_quad_spi_0_0/PmodJSTK2_axi_quad_spi_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodJSTK2_axi_quad_spi_0_0 || ORIG_REF_NAME==PmodJSTK2_axi_quad_spi_0_0}] {/U0 }]/U0 ]]

# XDC: c:/Users/Public/Vivado_Projects/Nexys-Video-HDMI/src/bd/hdmi/ip/hdmi_PmodJSTK2_1_0_1/src/PmodJSTK2_axi_quad_spi_0_0/PmodJSTK2_axi_quad_spi_0_0_ooc.xdc

# XDC: c:/Users/Public/Vivado_Projects/Nexys-Video-HDMI/src/bd/hdmi/ip/hdmi_PmodJSTK2_1_0_1/src/PmodJSTK2_axi_quad_spi_0_0/PmodJSTK2_axi_quad_spi_0_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodJSTK2_axi_quad_spi_0_0 || ORIG_REF_NAME==PmodJSTK2_axi_quad_spi_0_0}] {/U0 }]/U0 ]]

# XDC: c:/Users/Public/Vivado_Projects/Nexys-Video-HDMI/src/bd/hdmi/ip/hdmi_PmodJSTK2_1_0_1/src/PmodJSTK2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'hdmi_PmodJSTK2_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# IP: c:/Users/Public/Vivado_Projects/Nexys-Video-HDMI/src/bd/hdmi/ip/hdmi_PmodJSTK2_1_0_1/hdmi_PmodJSTK2_1_0.xci
# IP: The module: 'hdmi_PmodJSTK2_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/Public/Vivado_Projects/Nexys-Video-HDMI/src/bd/hdmi/ip/hdmi_PmodJSTK2_1_0_1/src/PmodJSTK2_pmod_bridge_0_0/PmodJSTK2_pmod_bridge_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PmodJSTK2_pmod_bridge_0_0 || ORIG_REF_NAME==PmodJSTK2_pmod_bridge_0_0}]

# IP: c:/Users/Public/Vivado_Projects/Nexys-Video-HDMI/src/bd/hdmi/ip/hdmi_PmodJSTK2_1_0_1/src/PmodJSTK2_axi_quad_spi_0_0/PmodJSTK2_axi_quad_spi_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PmodJSTK2_axi_quad_spi_0_0 || ORIG_REF_NAME==PmodJSTK2_axi_quad_spi_0_0}]

# XDC: c:/Users/Public/Vivado_Projects/Nexys-Video-HDMI/src/bd/hdmi/ip/hdmi_PmodJSTK2_1_0_1/hdmi_PmodJSTK2_1_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'hdmi_PmodJSTK2_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: c:/Users/Public/Vivado_Projects/Nexys-Video-HDMI/src/bd/hdmi/ip/hdmi_PmodJSTK2_1_0_1/src/PmodJSTK2_pmod_bridge_0_0/PmodJSTK2_pmod_bridge_0_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodJSTK2_pmod_bridge_0_0 || ORIG_REF_NAME==PmodJSTK2_pmod_bridge_0_0}] {/inst }]/inst ]]

# XDC: c:/Users/Public/Vivado_Projects/Nexys-Video-HDMI/src/bd/hdmi/ip/hdmi_PmodJSTK2_1_0_1/src/PmodJSTK2_pmod_bridge_0_0/src/pmod_concat_ooc.xdc

# XDC: c:/Users/Public/Vivado_Projects/Nexys-Video-HDMI/src/bd/hdmi/ip/hdmi_PmodJSTK2_1_0_1/src/PmodJSTK2_axi_quad_spi_0_0/PmodJSTK2_axi_quad_spi_0_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodJSTK2_axi_quad_spi_0_0 || ORIG_REF_NAME==PmodJSTK2_axi_quad_spi_0_0}] {/U0 }]/U0 ]]

# XDC: c:/Users/Public/Vivado_Projects/Nexys-Video-HDMI/src/bd/hdmi/ip/hdmi_PmodJSTK2_1_0_1/src/PmodJSTK2_axi_quad_spi_0_0/PmodJSTK2_axi_quad_spi_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodJSTK2_axi_quad_spi_0_0 || ORIG_REF_NAME==PmodJSTK2_axi_quad_spi_0_0}] {/U0 }]/U0 ]]

# XDC: c:/Users/Public/Vivado_Projects/Nexys-Video-HDMI/src/bd/hdmi/ip/hdmi_PmodJSTK2_1_0_1/src/PmodJSTK2_axi_quad_spi_0_0/PmodJSTK2_axi_quad_spi_0_0_ooc.xdc

# XDC: c:/Users/Public/Vivado_Projects/Nexys-Video-HDMI/src/bd/hdmi/ip/hdmi_PmodJSTK2_1_0_1/src/PmodJSTK2_axi_quad_spi_0_0/PmodJSTK2_axi_quad_spi_0_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodJSTK2_axi_quad_spi_0_0 || ORIG_REF_NAME==PmodJSTK2_axi_quad_spi_0_0}] {/U0 }]/U0 ]]

# XDC: c:/Users/Public/Vivado_Projects/Nexys-Video-HDMI/src/bd/hdmi/ip/hdmi_PmodJSTK2_1_0_1/src/PmodJSTK2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'hdmi_PmodJSTK2_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
